### ISSUE TITLE
Suporte ao DotNetCore

### ISSUE THREAD

**Issue by mateusdemboski** [NotaFiscalNet/NotaFiscalNet#52]
Avaliar a possibilidade de porte da biblioteca para que seja compatível com o netstandard2.0

**Comment by gmarcial** [comment]
:+1:

**Comment by williamthiago** [comment]
@mateusdemboski faz muito tempo que não tocava nesse projeto, estou retomando justamente para dar suporte a .net core e a próxima versão do schema.
